const Map<String, String> appStringsEn = {
  // App
  'appName': 'Warranty Wallet',
  'appTagline': 'Manage warranties, invoices & receipts',
  'skip': 'Skip',
  'next': 'Next',
  'getStarted': 'Get Started',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'confirm': 'Confirm',
  'close': 'Close',
  'search': 'Search devices...',
  'noResults': 'No devices found',
  'offlineNote': 'Works fully offline',

  // Onboarding
  'onboardingTitle1': 'Track Your Warranties',
  'onboardingDesc1': 'Save devices, serial numbers, purchase dates & warranty expiry — all stored securely on your device.',
  'onboardingTitle2': 'Never Miss Expiry',
  'onboardingDesc2': 'See expired warranties, items expiring soon, and plan ahead before coverage runs out.',
  'onboardingTitle3': 'Earn Coins & Customize',
  'onboardingDesc3': 'Add devices and invoices to earn coins. Unlock themes, skins, and premium features in the Shop.',

  // Navigation
  'navHome': 'Home',
  'navDevices': 'Devices',
  'navShop': 'Shop',
  'navSettings': 'Settings',

  // Home
  'homeGreeting': 'Hello!',
  'homeSubtitle': 'Your warranty dashboard',
  'homeQuickActions': 'Quick Actions',
  'homeMyDevices': 'My Devices',
  'homeNoDevicesYet': 'Add your first device to start tracking',
  'homeNoActivity': 'No devices yet — tap Add Device to begin',
  'homeViewAllDevices': 'View All',
  'expiringSoon': 'Expiring Soon',
  'expiredWarranties': 'Expired',
  'activeWarranties': 'Active',
  'totalDevices': 'Total Devices',
  'viewAll': 'View All',
  'noExpiringSoon': 'No warranties expiring soon',
  'noExpired': 'All warranties active!',
  'noWarrantyHint': 'Add a device with purchase date and warranty expiry to get started.',
  'noUpcoming': 'No upcoming expiries',
  'quickAdd': 'Add Device',
  'statsProLocked': 'Unlock Stats Pro in Shop',
  'expiresToday': 'Expires today',
  'expiresTomorrow': 'Expires tomorrow',
  'expiresInDays': 'Expires in {count} days',
  'daysExpired': '{count} days expired',
  'recentDevices': 'Recent Devices',
  'recentActivity': 'Recent Activity',

  // Device categories
  'catElectronics': 'Electronics',
  'catAppliance': 'Appliance',
  'catComputer': 'Computer',
  'catPhone': 'Phone',
  'catFurniture': 'Furniture',
  'catVehicle': 'Vehicle',
  'catOther': 'Other',

  // Devices
  'devicesTitle': 'My Devices',
  'addDevice': 'Add Device',
  'editDevice': 'Edit Device',
  'deviceName': 'Device Name',
  'deviceCategory': 'Category',
  'serialNumber': 'Serial Number',
  'invoiceNumber': 'Invoice Number',
  'storeName': 'Store / Seller',
  'purchaseDate': 'Purchase Date',
  'warrantyExpiry': 'Warranty Expiry',
  'deviceDetail': 'Device Details',
  'deleteDevice': 'Delete Device',
  'deleteDeviceConfirm': 'Remove this device and all photos?',
  'deviceLimitReached': 'Device limit reached ({limit}). Unlock unlimited in Shop.',
  'filterAll': 'All',
  'filterExpired': 'Expired',
  'filterExpiring': 'Expiring Soon',
  'filterActive': 'Active',
  'advancedFiltersLocked': 'Unlock Advanced Filters in Shop',
  'tags': 'Tags',
  'addTag': 'Add tag',
  'customTagsLocked': 'Unlock Custom Tags in Shop',
  'selectDate': 'Select date',
  'clearDate': 'Clear',
  'nameRequired': 'Name is required',
  'purchaseDateRequired': 'Purchase date is required',
  'warrantyDateRequired': 'Warranty expiry is required',
  'noSerial': 'No serial number',
  'noInvoice': 'No invoice number',
  'warrantyActive': 'Active',
  'warrantyExpiringSoon': 'Expiring Soon',
  'warrantyExpired': 'Expired',
  'daysLeft': '{count} days left',
  'warrantyMonths': '{count} month warranty',

  // Photos & Invoice
  'photos': 'Photos',
  'invoice': 'Invoice / Receipt',
  'addPhoto': 'Add Photo',
  'addInvoice': 'Add Invoice Photo',
  'removePhoto': 'Remove Photo',
  'photoLimitReached': 'Photo limit reached ({limit}). Unlock Multi Photos in Shop.',
  'notes': 'Notes',
  'noPhotos': 'No photos yet',
  'noInvoicePhoto': 'No invoice photo',

  // Shop
  'shopTitle': 'Coin Shop',
  'shopSubtitle': 'Earn coins or buy packs to unlock rewards',
  'yourCoins': 'Your coins: {count}',
  'buyCoins': 'Buy Coins',
  'buyCoinsDesc': 'Purchase coin packs via Google Play',
  'coinPack': 'Coin Pack {num}',
  'coinAmount': '{count} coins',
  'earnCoinsHint': 'Earn coins by daily login, adding devices & saving invoices',
  'shopEmptyCategory': 'Nothing here yet',
  'shopMenuPremium': 'Premium',
  'shopMenuAll': 'All',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Card Skins',
  'shopMenuFeatures': 'Features',
  'shopRemoveAds': 'Remove Ads',
  'shopRemoveAdsDesc': 'Hide banner ads permanently',
  'shopThemeSunset': 'Sunset Theme',
  'shopThemeSunsetDesc': 'Warm orange & coral tones',
  'shopThemeMidnight': 'Midnight Theme',
  'shopThemeMidnightDesc': 'Deep blue professional look',
  'shopThemeNeon': 'Neon Theme',
  'shopThemeNeonDesc': 'Vibrant purple & pink accents',
  'shopThemeOcean': 'Ocean Theme',
  'shopThemeOceanDesc': 'Fresh teal & aqua palette',
  'shopBgSunrise': 'Sunrise Background',
  'shopBgSunriseDesc': 'Golden morning gradient',
  'shopBgAurora': 'Aurora Background',
  'shopBgAuroraDesc': 'Northern lights blend',
  'shopBgGalaxy': 'Galaxy Background',
  'shopBgGalaxyDesc': 'Deep space purple glow',
  'shopBgFire': 'Fire Background',
  'shopBgFireDesc': 'Bold red-orange energy',
  'shopSkinGlass': 'Glass Skin',
  'shopSkinGlassDesc': 'Frosted glass card style',
  'shopSkinMinimal': 'Minimal Skin',
  'shopSkinMinimalDesc': 'Clean flat cards',
  'shopSkinBold': 'Bold Skin',
  'shopSkinBoldDesc': 'Rounded bold card design',
  'shopFeatUnlimitedDevices': 'Unlimited Devices',
  'shopFeatUnlimitedDevicesDesc': 'Remove the 5 device limit',
  'shopFeatAdvancedFilters': 'Advanced Filters',
  'shopFeatAdvancedFiltersDesc': 'Filter by expired, expiring, active & category',
  'shopFeatStatsPro': 'Stats Pro',
  'shopFeatStatsProDesc': 'Detailed warranty dashboard with analytics',
  'shopFeatExport': 'Export Data',
  'shopFeatExportDesc': 'Share warranty data as CSV',
  'shopFeatWarrantyAlert': 'Warranty Alert Badge',
  'shopFeatWarrantyAlertDesc': 'Highlight urgent expiring warranties on home',
  'shopFeatCustomTags': 'Custom Tags',
  'shopFeatCustomTagsDesc': 'Organize devices with color tags',
  'shopFeatMultiPhotos': 'Multi Photos',
  'shopFeatMultiPhotosDesc': 'Save up to 10 photos per device',
  'insufficientCoins': 'Not enough coins',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'alreadyOwned': 'Already owned',
  'dailyReward': 'Daily Reward',
  'dailyRewardClaim': 'Claim {count} coins',
  'dailyRewardClaimed': 'Daily reward claimed!',
  'dailyRewardDone': 'Claimed today',

  // IAP / Billing
  'billingDisabled': 'Google Play purchases are temporarily unavailable',
  'billingUnavailable': 'Billing not available on this device',
  'productsNotFound': 'Products not configured yet',
  'processingPurchase': 'Processing purchase...',
  'openingBilling': 'Opening Google Play...',
  'restoringPurchases': 'Restoring purchases...',
  'restoreComplete': 'Restore complete',
  'restorePurchases': 'Restore Purchases',
  'restorePurchasesDesc': 'Restore previous Google Play purchases',
  'configNetworkError': 'Could not reach server. Using cached settings.',
  'configTimeout': 'Server timeout. Using cached settings.',
  'coinsAdded': 'Coins added to your balance!',
  'deviceAddedReward': '+10 coins for new device',
  'photoAddedReward': '+5 coins for adding photo',
  'invoiceAddedReward': '+5 coins for saving invoice',

  // Settings
  'settingsTitle': 'Settings',
  'appearance': 'Appearance',
  'darkMode': 'Dark Mode',
  'activeTheme': 'Active Theme',
  'activeBackground': 'Active Background',
  'activeSkin': 'Active Card Skin',
  'activeCustomization': 'Active Customization',
  'resetToDefault': 'Reset to Default',
  'resetDefault': 'Reset to default style',
  'data': 'Data',
  'exportDevices': 'Export Warranty Data',
  'exportLocked': 'Unlock Export in Shop',
  'about': 'About',
  'version': 'Version {version}',
  'privacyPolicy': 'Privacy Policy',
  'openShop': 'Open Shop',
  'openShopDesc': 'Themes, skins & features',
  'removeAdsActive': 'Banner ads are hidden',
  'statsProActive': 'Full dashboard unlocked',
  'warrantyAlertActive': 'Urgent warranties highlighted',
  'customTagsActive': 'Color tags enabled',
  'multiPhotosActive': 'Up to 10 photos per device',
  'aboutDesc': 'Warranty & invoice manager — track expiry dates offline',
  'copyright': '© Warranty Wallet',

  // Shop missions
  'earnCoins': 'Earn Coins',
  'earnStepDaily': 'Daily login bonus',
  'claimDailyButton': 'Claim',
  'earnStepAddDevice': 'Add a device',
  'earnStepAddDeviceDesc': '+10 coins each',
  'earnStepAddPhoto': 'Save photo or invoice',
  'earnStepAddPhotoDesc': '+5 coins each',
  'earnStepBuy': 'Buy coin packs',
  'buyWithGooglePlay': 'Google Play',
  'yourWallet': 'Your Wallet',
  'coinsLabel': 'coins',
  'shopBrowse': 'Browse Rewards',
  'owned': 'Owned',
  'apply': 'Apply',
  'applied': 'Applied!',
  'active': 'Active',
  'adLabel': 'Ad',
  'adPlaceholder': 'Advertisement',
  'adRemoved': 'Ads removed',

  // Privacy
  'privacyTitle': 'Privacy Policy',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody': 'Warranty Wallet stores all device, warranty, and invoice data locally on your device. We do not collect, transmit, or sell your personal information.\n\n'
      'Optional in-app purchases are processed by Google Play. Coin balances and purchased items are stored locally.\n\n'
      'The app may fetch a remote configuration file to enable or disable Google Play billing. No device data is sent in this request.\n\n'
      'Contact: support@warrantywallet.app',
};
